# Generated by Django 4.0.4 on 2022-09-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_category_event_subcategory_product_eventproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SubCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotation.subcategory'),
        ),
    ]
