# Generated by Django 4.0.4 on 2022-09-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.IntegerField(blank=True)),
                ('theatre', models.IntegerField(blank=True)),
                ('tent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotation.product')),
            ],
        ),
    ]
