# Generated by Django 4.0.4 on 2022-09-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='population',
            new_name='guests',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
