# Generated by Django 4.0.4 on 2022-09-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0010_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
