# Generated by Django 4.0.4 on 2022-09-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='SubCategory',
            new_name='subcategory',
        ),
    ]
